DROP TABLE IF EXISTS repeaters;

DROP TABLE IF EXISTS requests;

DROP TABLE IF EXISTS changelog;

CREATE TABLE
    IF NOT EXISTS repeaters (
        callsign TEXT NOT NULL PRIMARY KEY,
        disabled INTEGER NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        keeper TEXT NOT NULL,
        latitude NUMERIC(3, 8) NOT NULL,
        longitude NUMERIC(3, 8) NOT NULL,
        place TEXT NOT NULL,
        location TEXT,
        info TEXT,
        altitude INTEGER NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        power INTEGER NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        mode_fm BOOLEAN NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        mode_am BOOLEAN NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        mode_usb BOOLEAN NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        mode_lsb BOOLEAN NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        mode_dmr BOOLEAN NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        mode_dstar BOOLEAN NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        mode_fusion BOOLEAN NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        mode_nxdn BOOLEAN NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        mode_parrot BOOLEAN NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        mode_beacon BOOLEAN NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        freq_rx INTEGER NOT NULL,
        freq_tx INTEGER NOT NULL,
        tone NUMERIC(3, 1) NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        net_echolink INTEGER NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        net_allstarlink INTEGER NOT NULL ON CONFLICT REPLACE DEFAULT 0,
        net_zello TEXT,
        net_other TEXT,
        coverage_map_json TEXT,
        created DATETIME NOT NULL ON CONFLICT REPLACE DEFAULT CURRENT_TIMESTAMP,
        updated DATETIME NOT NULL ON CONFLICT REPLACE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE
    requests (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        contact TEXT NOT NULL,
        info TEXT NOT NULL,
        date DATETIME NOT NULL ON CONFLICT REPLACE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE
    changelog (
        date DATETIME PRIMARY KEY NOT NULL ON CONFLICT REPLACE DEFAULT CURRENT_TIMESTAMP,
        who TEXT NOT NULL,
        info TEXT NOT NULL
    );
